### ISSUE TITLE
Installing “autocomplete-python@1.8.7” failed.Hide output…

### ISSUE THREAD

**Issue by zssr** [autocomplete-python/autocomplete-python#242]
here is output:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: unexpected eof
gyp ERR! stack     at decorate (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/fstream/lib/abstract.js:67:36)
gyp ERR! stack     at Extract.Abstract.error (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/fstream/lib/abstract.js:61:12)
gyp ERR! stack     at Extract._streamEnd (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/tar/lib/extract.js:91:35)
gyp ERR! stack     at BlockStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/tar/lib/parse.js:51:8)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at BlockStream.emit (events.js:166:7)
gyp ERR! stack     at BlockStream._emitChunk (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/block-stream/block-stream.js:203:10)
gyp ERR! stack     at BlockStream.flush (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/block-stream/block-stream.js:70:8)
gyp ERR! stack     at BlockStream.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/block-stream/block-stream.js:66:8)
gyp ERR! stack     at Extract.Parse.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/tar/lib/parse.js:86:23)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=0.37.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/vin/.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

what can i do to fix it?

**Comment by sadovnychyi** [comment]
Re-install the package? Or manually from `~/.atom/packages/autocomplete-python`

```
apm install
```

It's likely due to network error `unexpected eof` one of dependencies got corrupted. I don't know how apm/npm handle this.

**Comment by zssr** [comment]
@sadovnychyi here is what i tried: 
* `cd ~/.atom/packages/`
* `git clone https://github.com/autocomplete-python/autocomplete-python.git`
* `cd autocomplete-python`
* `apm install`

the last command line generated this:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at TCP.onread (net.js:552:26)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=0.37.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/vin/.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by sadovnychyi** [comment]
Possible related https://github.com/atom/atom/issues/11080
Are you in China? Can you access that URL? (https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz)
