### ISSUE TITLE
Uncaught TypeError: Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by uygunuks** [autocomplete-python/autocomplete-python#263]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package, v1.8.23

### Stack Trace

Uncaught TypeError: Cannot read property 'test' of undefined

```
At /Users/uygun/.atom/packages/autocomplete-python/lib/provider.coffee:428

TypeError: Cannot read property 'test' of undefined
    at constructor.getSuggestions (/Users/uygun/.atom/packages/autocomplete-python/lib/provider.coffee:428:35)
    at /Users/uygun/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/uygun/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Users/uygun/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:59)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/uygun/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /Users/uygun/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:59
```

### Commands

```
     -0:00.8.0 core:cut (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "autocomplete-python": {
    "useKite": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (active)
atom-django, v0.3.2 (active)
autocomplete-angular-material, v0.4.0 (active)
autocomplete-python, v1.8.23 (active)
django-templates, v0.5.0 (active)
language-django, v0.1.1 (active)
language-python-django-templates, v0.1.0 (active)
python-tools, v0.6.8 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dpmontero** [comment]
Hi!,

The same problem in Linux:
`TypeError: Cannot read property 'test' of undefined
    at constructor.getSuggestions (/home/diego/.atom/packages/autocomplete-python/lib/provider.coffee:428:35)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:59)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:59`

**Comment by henri-hulski** [comment]
Here the same on Debian Jessie:

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Debian GNU/Linux
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package, v1.8.24


### Stack Trace

Uncaught TypeError: Cannot read property 'test' of undefined

```
At /home/pacha/.atom/packages/autocomplete-python/lib/provider.coffee:428

TypeError: Cannot read property 'test' of undefined
    at constructor.getSuggestions (/home/pacha/.atom/packages/autocomplete-python/lib/provider.coffee:428:35)
    at /home/pacha/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:242:52
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/home/pacha/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:218:15)
    at AutocompleteManager.findSuggestions (/home/pacha/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:210:17)
```

### Commands

```
  2x -9:33.4.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -9:32.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:51.3.0 core:copy (atom-text-editor.editor.is-focused)
     -8:42.7.0 core:paste (atom-text-editor.editor.is-focused)
     -8:39.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:16.8.0 core:paste (atom-text-editor.editor.is-focused)
     -8:03.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:57.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -7:54.1.0 core:paste (atom-text-editor.editor.is-focused)
     -7:41.1.0 tree-view:move (span.name.icon.icon-file-text)
     -7:39.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -7:38.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:26.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:26.4.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -4:39.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:20 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics",
      "php-debug",
      "minimap",
      "minimap-bookmarks",
      "minimap-cursorline",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-linter",
      "minimap-split-diff"
    ],
    "ignoredNames": [
      "*.pyc",
      "*.pyo"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "atom-cerebral-signal-bootstrap",
      "standard-formatter"
    ],
    "projectHome": "/home/pacha/web/atom",
    "telemetryConsent": "no"
  },
  "autocomplete-python": {
    "useKite": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.14 (active)
atom-cerebral-signal-bootstrap, v1.3.0 (inactive)
atom-django, v0.3.2 (active)
atom-html-preview, v0.1.22 (active)
atom-htmltidy, v5.1.0 (active)
atom-meld, v0.2.1 (active)
atom-notifier, v0.5.1 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-plus, v2.34.2 (active)
autocomplete-python, v1.8.24 (active)
autosave-plus, v0.5.2 (active)
genesis-ui, v0.5.0 (inactive)
git-plus, v6.3.0 (active)
git-time-machine, v1.5.4 (inactive)
gtk-dark-theme, v0.1.4 (active)
icon-fonts, v2.11.0 (active)
js-refactor, v0.7.5 (active)
language-babel, v2.48.5 (active)
language-buildout, v0.1.1 (active)
language-django, v0.1.1 (active)
language-gitignore, v0.3.0 (active)
language-restructuredtext, v1.0.1 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-eslint, v8.0.0 (active)
linter-flake8, v2.1.4 (inactive)
linter-js-standard-jsx, v4.1.2 (active)
linter-php, v1.3.1 (active)
linter-sass-lint, v1.7.4 (active)
local-history, v3.4.1 (active)
node-debug, v0.1.7 (inactive)
node-debugger, v1.9.2 (active)
open-in-browser, v0.4.7 (inactive)
php-cs-fixer, v4.1.0 (active)
pigments, v0.37.0 (active)
platformio-ide-terminal, v2.2.2 (active)
project-plus, v0.9.0 (active)
python-debugger, v0.1.0 (inactive)
python-indent, v1.0.0 (active)
python-isort, v0.0.7 (active)
python-tools, v0.6.8 (active)
refactor, v0.11.3 (active)
rst-preview-pandoc, v0.1.12 (active)
semantic-ui, v1.0.8 (active)
slim-dark-ui, v0.12.0 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.1.0 (inactive)
standard-formatter, v2.6.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
uglify, v1.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.34.2 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Should be fixed. Please let me know if it's still appears.

**Comment by shaashwat** [comment]
The same error still appears for me.

**Comment by sadovnychyi** [comment]
@shaashwat can you provide the traceback please? At which line did it appear?

**Comment by shaashwat** [comment]
Whoops, atom quit unexpectedly while it was updating. I uninstalled and reinstalled and it works now!

Thanks!
