### ISSUE TITLE
Autocomplete doesn't work after upgrade to python3.6

### ISSUE THREAD

**Issue by nitipit** [autocomplete-python/autocomplete-python#265]
### Steps to Reproduce
1. Install python3.6 from source (Linux: fedora 25).
2. open a python file, autocomplete doesn't work.

The issue is related to python-jedi https://github.com/davidhalter/jedi/issues/820
Debug log below:
```
autocomplete-python: autocomplete-python traceback output: Traceback (most recent call last):
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/parser/__init__.py", line 56, in load_grammar
    return _loaded_grammars[path]
KeyError: '/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/parser/grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/completion.py", line 374, in watch
    self._process_request(self._input.readline())
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/completion.py", line 342, in _process_request
    column=request['column'], path=request.get('path', ''))
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 126, in __init__
    self._grammar = load_grammar(version='%s.%s' % sys.version_info[:2])
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/parser/__init__.py", line 58, in load_grammar
    return _loaded_grammars.setdefault(path, generate_grammar(path))
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/parser/pgen2/pgen.py", line 393, in generate_grammar
    p = ParserGenerator(filename)
  File "/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/parser/pgen2/pgen.py", line 18, in __init__
    stream = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nitipit/.atom/packages/autocomplete-python/lib/jedi/parser/grammar3.6.txt'
```

**Comment by sadovnychyi** [comment]
Going to wait until it's fixed in Jedi.
