### ISSUE TITLE
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

### ISSUE THREAD

**Issue by justinsolms** [autocomplete-python/autocomplete-python#278]
1. Type a docstring.
2. When presented with autocomplete option, press <enter> which raises the exception.

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package, v1.8.28

### Stack Trace

Uncaught TypeError: Array.prototype.indexOf called on null or undefined

```
At /home/sunstrike/.atom/packages/autocomplete-python/lib/main.coffee:305

TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (native)
    at Object.trackUsedSuggestion (/home/sunstrike/.atom/packages/autocomplete-python/lib/main.coffee:305:12)
    at AutocompleteManager.autocompleteManager.confirm (/home/sunstrike/.atom/packages/autocomplete-python/lib/main.coffee:268:10)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:16
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at SuggestionList.confirm (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:135:27)
    at autocomplete-suggestion-list.confirmSelection (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:313:27)
    at autocomplete-suggestion-list.onmouseup (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:146:18)
```

### Commands

```
     -0:27.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-justin-light-syntax.theme-atom-light-ui)
     -0:17.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:17.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:17 markdown-writer:insert-new-line (input.hidden-input)
     -0:17 autocomplete-plus:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "symbols-view"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".pyc"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/home/sunstrike/Documents/Python",
    "telemetryConsent": "limited",
    "themes": [
      "atom-light-ui",
      "justin-light-syntax"
    ]
  },
  "autocomplete-python": {
    "useKite": false,
    "useSnippets": "all"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (inactive)
atom-ctags, v5.0.0 (active)
autocomplete-python, v1.8.28 (active)
autocomplete-xml, v0.9.4 (active)
ctags-status, v1.3.7 (active)
file-icons, v2.0.12 (active)
find-and-replace, v0.206.1 (inactive)
github-atom-light-syntax, v0.3.2 (inactive)
highlight-selected, v0.12.0 (active)
imdone-atom, v2.1.12 (active)
justin-light-syntax, v0.1.0 (active)
keybinding-cheatsheet, v0.1.1 (inactive)
language-csv, v1.1.2 (active)
language-markdown, v0.19.1 (active)
language-restructuredtext, v1.0.1 (active)
linter, v1.11.21 (active)
linter-flake8, v2.1.4 (active)
markdown-writer, v2.6.3 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.7 (active)
pandoc-convert, v1.1.0 (active)
pen-paper-coffee-syntax, v0.14.8 (inactive)
pigments, v0.39.0 (active)
python-indent, v1.0.0 (active)
symbols-tree-view, v0.13.2 (active)
tablr, v1.8.1 (active)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (active)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.206.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by colago** [comment]
Same here with normal strings.

**Comment by gad2103** [comment]
having the same problem just showed up today...

**Comment by twof** [comment]
Also having this problem. 
![image](https://cloud.githubusercontent.com/assets/5561501/22444251/083ed1c6-e6f7-11e6-8a08-9a307cad28bb.png)

Error triggers when hitting return. The autocompleted phrase is the name of a function further down in the file.

**Comment by acerv** [comment]
I confirm the bug. Same for me on Debian 8.7, latest Atom version, mostly used for python 3.5 scripting.

**Comment by danielunderwood** [comment]
I'm running into the same error.

**Atom** 1.14.1
**autocomplete-python** 1.8.50
**Platform** Arch, atom installed with aur
