### ISSUE TITLE
Uncaught TypeError: Cannot create property 'buttonPosition' on string 'trialPrime'

### ISSUE THREAD

**Issue by annelisehitchman** [autocomplete-python/autocomplete-python#279]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.1
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package, v1.8.28

### Stack Trace

Uncaught TypeError: Cannot create property 'buttonPosition' on string 'trialPrime'

```
At /Users/annelisehitchman/.atom/packages/autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:49

TypeError: Cannot create property 'buttonPosition' on string 'trialPrime'
    at Object.trackEvent (/Users/annelisehitchman/.atom/packages/autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:49:19)
    at Object.track (/Users/annelisehitchman/.atom/packages/autocomplete-python/lib/main.coffee:314:21)
    at Object.trackUsedSuggestion (/Users/annelisehitchman/.atom/packages/autocomplete-python/lib/main.coffee:306:12)
    at AutocompleteManager.autocompleteManager.confirm (/Users/annelisehitchman/.atom/packages/autocomplete-python/lib/main.coffee:268:10)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at SuggestionList.confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:135:27)
    at autocomplete-suggestion-list.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:313:27)
    at autocomplete-suggestion-list.onmouseup (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:146:18)
```

### Commands

```
     -5:53.7.0 autocomplete-plus:activate (atom-text-editor.editor)
     -5:38.8.0 core:backspace (input.hidden-input)
  3x -5:36.4.0 core:move-right (input.hidden-input)
     -5:35.4.0 core:save (input.hidden-input)
     -4:56.3.0 core:save-as (input.hidden-input)
     -4:23.8.0 autocomplete-plus:activate (atom-text-editor.editor)
  2x -4:22 core:save (input.hidden-input)
  3x -1:40.6.0 core:backspace (input.hidden-input)
     -1:12.6.0 core:save (input.hidden-input)
     -0:38.8.0 editor:newline (input.hidden-input)
     -0:31.9.0 autocomplete-plus:activate (atom-text-editor.editor)
     -0:31.3.0 editor:newline (input.hidden-input)
     -0:30.9.0 core:backspace (input.hidden-input)
     -0:29.8.0 editor:newline (input.hidden-input)
     -0:25.6.0 core:save (input.hidden-input)
     -0:22 autocomplete-plus:confirm (input.hidden-input)
```

### Config

```json
{
  "autocomplete-python": {
    "useKite": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.28 (active)
linter, v1.11.21 (active)
linter-pylint, v1.2.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dhung09** [comment]
cc @abe33
