### ISSUE TITLE
Uncaught TypeError: crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by nikaro** [autocomplete-python/autocomplete-python#281]
[Enter steps to reproduce below:]

1. Try to use autocompletion.

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package, v1.8.42

### Stack Trace

Uncaught TypeError: crypto.randomBytes is not a function

```
At /home/nicolas/.atom/packages/autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:25

TypeError: crypto.randomBytes is not a function
    at distinctID (/home/nicolas/.atom/packages/autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:25:32)
    at track (/home/nicolas/.atom/packages/autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:34:18)
    at Object.trackEvent (/home/nicolas/.atom/packages/autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:59:5)
    at Object.track (/home/nicolas/.atom/packages/autocomplete-python/lib/main.coffee:322:21)
    at Object.trackUsedSuggestion (/home/nicolas/.atom/packages/autocomplete-python/lib/main.coffee:313:12)
    at AutocompleteManager.autocompleteManager.confirm (/home/nicolas/.atom/packages/autocomplete-python/lib/main.coffee:276:10)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:16
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at SuggestionList.confirm (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:135:27)
    at autocomplete-suggestion-list.confirmSelection (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:313:27)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at SuggestionList.confirmSelection (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:140:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:50.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-light-ui)
  2x -0:03.7.0 core:move-left (input.hidden-input)
     -0:00.4.0 core:move-down (input.hidden-input)
     -0:00.1.0 autocomplete-plus:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "/home/nicolas/Projets",
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "autocomplete-python": {
    "pythonPaths": "/home/nicolas/.virtualenvs/$PROJECT_NAME/bin/python;$PROJECT/.venv/bin/python;$PROJECT/.env/bin/python;$PROJECT/venv/bin/python;$PROJECT/env/bin/python;/usr/bin/python3",
    "useKite": false,
    "useSnippets": "required"
  }
}
```

**Comment by nikaro** [comment]
Everything was working fine before i set `useKite` to false and updated my `pythonPaths`. But now, even if i rollback these changes, it still does not work.

**Comment by imgurbot12** [comment]
I am having the same issue and the package has become unusable in its current state.

**Comment by MichaelAquilina** [comment]
I've rolled back to `1.8.42` for now. You can do the same with the following command `apm install autocomplete-python@1.8.42`

**Comment by nikaro** [comment]
The problem also occurred on my computer at work, i had to rollback to 1.8.40 to make it work again.

**Comment by orlra** [comment]
autocomplete-python/node_modules/kite-installer/ext/telemetry/metrics.js:25
problem appeared when I tried to disable  
"Use kite powered completions"
I cannot disable this feature (both checked and unchecked throws same error).
autocomplete-python@1.8.43 ubuntu16.04
