### ISSUE TITLE
Start-up Error Probably due to Space in Directory

### ISSUE THREAD

**Issue by pingshunhuangalex** [autocomplete-python/autocomplete-python#282]
I noticed recently that when I start Atom, `autocomplete-python` seems to be reluctant to start up probably due to the space I have in my user directory? I've seen a couple of closed issues which recently reported similar issues. Hope it can be fixed soon. Thanks.

I'm using Win10 64-bit with Atom 1.14.0 beta4 64-bit.

```
Error: Command failed: C:\Users\Pingshun Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\read-arch.bat
'C:\Users\Pingshun' is not recognized as an internal or external command,
operable program or batch file.
    at checkExecSyncError (child_process.js:495:13)
    at Object.execSync (child_process.js:535:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at Object.arch (C:\Users\Pingshun Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\windows.js:63:33)
    at Object.isKiteSupported (C:\Users\Pingshun Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\windows.js:68:17)
    at Object.isKiteSupported (C:\Users\Pingshun Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\state-controller.js:51:25)
    at Object.canInstallKite (C:\Users\Pingshun Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\state-controller.js:65:17)
    at file:///C:/Users/Pingshun Huang/.atom/packages/autocomplete-python/lib/main.coffee:166:36
    at Object._loadKite (file:///C:/Users/Pingshun Huang/.atom/packages/autocomplete-python/lib/main.coffee:197:5)
    at Object.load (file:///C:/Users/Pingshun Huang/.atom/packages/autocomplete-python/lib/main.coffee:214:6)
    at Object.activate (file:///C:/Users/Pingshun Huang/.atom/packages/autocomplete-python/lib/main.coffee:222:8)
    at Package.module.exports.Package.activateNow (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package.js:218:19)
    at C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package.js:96:15)
    at C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package-manager.js:352:19
    at C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\config.js:826:29)
    at Config.module.exports.Config.setRawValue (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\config.js:612:19)
    at Config.module.exports.Config.set (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\package-manager.js:173:14)
    at HTMLButtonElement.<anonymous> (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\settings-view\lib\package-card.js:348:27)
    at HTMLButtonElement.dispatch (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\Pingshun Huang\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by sadovnychyi** [comment]
Can you check in 1.8.53 please? It should be fixed.

**Comment by pingshunhuangalex** [comment]
Hi @sadovnychyi 
I just updated to `1.8.53`, and activating the Kite-powered completions will still give me the below errors (Note again I'm using the latest Atom Beta and Windows 10 instead of Mac):
```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0-beta2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package 1.8.53


### Stack Trace

Uncaught Error: Command failed: C:\Users\Pingshun\ Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\read-arch.bat
'C:\Users\Pingshun\' is not recognized as an internal or external command,
operable program or batch file.


```
At child_process.js:538

Error: Command failed: C:\Users\Pingshun\ Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\read-arch.bat
'C:\Users\Pingshun\' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:495:13)
    at Object.execSync (child_process.js:535:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at Object.arch (/packages/autocomplete-python/node_modules/kite-installer/lib/support/windows.js:64:33)
    at Object.isKiteSupported (/packages/autocomplete-python/node_modules/kite-installer/lib/support/windows.js:69:17)
    at Object.isKiteSupported (/packages/autocomplete-python/node_modules/kite-installer/lib/state-controller.js:54:25)
    at Object.canInstallKite (/packages/autocomplete-python/node_modules/kite-installer/lib/state-controller.js:70:17)
    at /packages/autocomplete-python/lib/main.coffee:172:36
    at /packages/autocomplete-python/lib/main.coffee:207:9
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/app.asar/node_modules/settings-view/lib/settings-panel.js:201:28)
    at setNewValue (/app.asar/node_modules/settings-view/lib/settings-panel.js:137:28)
    at /app.asar/node_modules/settings-view/lib/settings-panel.js:143:22)
    at HTMLInputElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:08.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -0:56.4.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aligner 0.22.3 
atom-beautify 0.29.17 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-terminal 0.8.0 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.53 
autoprefixer 3.6.1 
color-picker 2.2.5 
d3-snippets 0.2.0 
django-atom 0.2.4 
emmet 2.4.3 
file-icons 2.0.15 
git-log 0.4.1 
git-plus 7.2.2 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
Hydrogen 1.5.5 
hyperclick 0.0.40 
js-hyperclick 1.10.1 
language-babel 2.54.1 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-csslint 1.3.3 
linter-eslint 8.1.1 
linter-flake8 2.1.4 
linter-jsonlint 1.3.0 
linter-markdown 3.1.0 
linter-xmllint 1.4.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-pigments 0.2.2 
pigments 0.39.0 
project-manager 3.3.3 
qolor 0.4.1 
regex-railroad-diagram 0.16.0 
sync-settings 0.8.1 
tree-view-git-status 1.3.0 
```


```

**Comment by sadovnychyi** [comment]
Well the error message did change at least, from `C:\Users\Pingshun` to `C:\Users\Pingshun\` – seems like escaping the space didn't help.

Could you try to edit `/packages/autocomplete-python/node_modules/kite-installer/lib/support/windows.js:64` (somewhere in your home folder I guess)

On line 64
```
return String(child_process.execSync(ARCH_BAT)).trim();
```

to

```
return String(child_process.execSync('read-arch.bat', {cwd: ESCAPED_DIRNAME})).trim();
```

Not sure that it's going to work, but it could.

https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

**Comment by pingshunhuangalex** [comment]
Now it becomes something like this:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0-beta2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package 1.8.53


### Stack Trace

Uncaught Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOENT

```
At child_process.js:538

Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at Object.execSync (child_process.js:529:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at Object.arch (/packages/autocomplete-python/node_modules/kite-installer/lib/support/windows.js:64:33)
    at Object.isKiteSupported (/packages/autocomplete-python/node_modules/kite-installer/lib/support/windows.js:69:17)
    at Object.isKiteSupported (/packages/autocomplete-python/node_modules/kite-installer/lib/state-controller.js:54:25)
    at Object.canInstallKite (/packages/autocomplete-python/node_modules/kite-installer/lib/state-controller.js:70:17)
    at /packages/autocomplete-python/lib/main.coffee:172:36
    at /packages/autocomplete-python/lib/main.coffee:207:9
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/app.asar/node_modules/settings-view/lib/settings-panel.js:201:28)
    at setNewValue (/app.asar/node_modules/settings-view/lib/settings-panel.js:137:28)
    at /app.asar/node_modules/settings-view/lib/settings-panel.js:143:22)
    at HTMLInputElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:49.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -0:28.1.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aligner 0.22.3 
atom-beautify 0.29.17 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-terminal 0.8.0 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.53 
autoprefixer 3.6.1 
color-picker 2.2.5 
d3-snippets 0.2.0 
django-atom 0.2.4 
emmet 2.4.3 
file-icons 2.0.15 
git-log 0.4.1 
git-plus 7.2.2 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
Hydrogen 1.5.5 
hyperclick 0.0.40 
js-hyperclick 1.10.1 
language-babel 2.54.1 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-csslint 1.3.3 
linter-eslint 8.1.1 
linter-flake8 2.1.4 
linter-jsonlint 1.3.0 
linter-markdown 3.1.0 
linter-xmllint 1.4.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-pigments 0.2.2 
pigments 0.39.0 
project-manager 3.3.3 
qolor 0.4.1 
regex-railroad-diagram 0.16.0 
sync-settings 0.8.1 
tree-view-git-status 1.3.0 
```

Also, now when the `windows.js` file gets load the below error pops up:
```
Error: Cannot find module 'eslint-config-fbjs' Referenced from: C:\Users\Pingshun Huang.atom\packages\autocomplete-python\node_modules\kite-installer.eslintrc.js
Error: Cannot find module 'eslint-config-fbjs'
Referenced from: C:\Users\Pingshun Huang\.atom\packages\autocomplete-python\node_modules\kite-installer\.eslintrc.js
    at ModuleResolver.resolve (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:478:25)
    at load (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:495:26)
    at configExtends.reduceRight.e (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:362:28)
    at Object.load (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:529:22)
    at loadConfig (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:63:33)
    at new Config (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:229:42)
    at CLIEngine.executeOnText (C:\Users\Pingshun Huang\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:741:28)
```

**Comment by sadovnychyi** [comment]
cc @abe33
