### ISSUE TITLE
Infinite recursion in _get_top_level_module

### ISSUE THREAD

**Issue by magv** [autocomplete-python/autocomplete-python#292]
Hi. Here's a problem:

1. Create file `__init__.py` in drive `C:\` on Windows or in `/` on a Unix.
2. Add `C:\` or `/` as a project directory in Atom and open `__init__.py`.
3. Type "abc." and press Ctrl-Space (or activate autocompletion any othe way).
4. You'll get an error like this one:
```
Traceback (most recent call last):
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 374, in watch
    self._process_request(self._input.readline())
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 335, in _process_request
    path = self._get_top_level_module(request.get('path', ''))
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 60, in _get_top_level_module
    return cls._get_top_level_module(_path)
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 60, in _get_top_level_module
    return cls._get_top_level_module(_path)
[...]
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 60, in _get_top_level_module
    return cls._get_top_level_module(_path)
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 60, in _get_top_level_module
    return cls._get_top_level_module(_path)
  File "~\.atom\packages\autocomplete-python\lib/completion.py", line 58, in _get_top_level_module
    _path, _ = os.path.split(path)
  File "C:\Program Files\Python35-32\lib\ntpath.py", line 204, in split
    d, p = splitdrive(p)
  File "C:\Program Files\Python35-32\lib\ntpath.py", line 139, in splitdrive
    if len(p) >= 2:
RecursionError: maximum recursion depth exceeded in comparison
```
I'm seeing this with autocomplete-python 1.8.54.

* * *

The source of the problem is this part of [lib/completion.py](//github.com/autocomplete-python/autocomplete-python/blob/v1.8.54/lib/completion.py#L51):
```python
    @classmethod
    def _get_top_level_module(cls, path):
        """Recursively walk through directories looking for top level module.
        Jedi will use current filepath to look for another modules at same
        path, but it will not be able to see modules **above**, so our goal
        is to find the higher python module available from filepath.
        """
        _path, _ = os.path.split(path)
        if os.path.isfile(os.path.join(_path, '__init__.py')):
            return cls._get_top_level_module(_path)
        return path
```

Since `os.path.split("C:\\")` is `('C:\\', '')` (similarly, `os.path.split("/")` is `('/', '')`), this leads to infinite recursion.

* * *

Here's the proposed solution:
```diff
--- completion.py.orig	2017-02-20 15:55:38 +0200
+++ completion.py	2017-02-22 12:53:10 +0200
@@ -56,6 +56,8 @@
         is to find the higher python module available from filepath.
         """
         _path, _ = os.path.split(path)
-        if os.path.isfile(os.path.join(_path, '__init__.py')):
+        if _path != path and os.path.isfile(os.path.join(_path, '__init__.py')):
             return cls._get_top_level_module(_path)
         return path
```

**Comment by sadovnychyi** [comment]
Thanks! Fixed.
