### ISSUE TITLE
Not working in Linux GalliumOS

### ISSUE THREAD

**Issue by huargovfx** [autocomplete-python/autocomplete-python#302]
Good day, after installing the autocomplete-python package, no message is appears to let me choose between kite or jedi. And it doesnt show anything when scripting in python. No box, help nothing.
I am using lastest version of Atom and autocomplete-python for GalliumOS

### Prerequisites

* [ ] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by sadovnychyi** [comment]
Anything in logs?

**Comment by huargovfx** [comment]
It doesnt show anything, after the installation nothing happens.

**Comment by huargovfx** [comment]
No logs or error

**Comment by sadovnychyi** [comment]
Are you sure that you are using built-in Python grammar? e.g. you have no custom plugins for python syntax or something. Try to switch to plain-text and back to python grammar. [Something](https://github.com/autocomplete-python/autocomplete-python/blob/master/lib/provider.coffee#L114) has to appear in the logs. You did check the checkbox in plugin settings to enable debug logs right?

**Comment by huargovfx** [comment]
Got this


task.coffee:84 spell-check:en-ca Can't load en_CA: Cannot find dictionary for en_CA.
https://api.travis-ci.org/autocomplete-python/autocomplete-python.svg?branch=master Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
package-manager.coffee:149 Uncaught (in promise) Error: Fetching outdated packages and themes failed.(…)
2package-card.coffee:477 Installing package autocomplete-python failed Error: Installing “autocomplete-python@1.8.63” failed.
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:496:21
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12) Request for package information failed: getaddrinfo EAI_AGAIN atom.io:443 (EAI_AGAIN)
(anonymous function) @ package-card.coffee:477
4package-manager.coffee:415 Could not resolve 'kite' to a package path
logger.js:71 request#1 error occured Error: getaddrinfo EAI_AGAIN plugins.kite.com:443(…) ClientRequestlog @ logger.js:71
logger.js:71 request#2 error occured Error: getaddrinfo EAI_AGAIN plugins.kite.com:443(…) ClientRequestlog @ logger.js:71
log.coffee [sm]:5 autocomplete-python: Killing python process after timeout...
2log.coffee [sm]:5 autocomplete-python: Ignoring keyup events due to autocomplete-plus settings.

**Comment by sadovnychyi** [comment]
@abe33 could be something related to kite, but I'm not sure. `package-manager.coffee:415 Could not resolve 'kite' to a package path`

**Comment by huargovfx** [comment]
Fixed those errors installing  nodejs and npm but still nothing happens and the log is empty this time.

**Comment by huargovfx** [comment]
got this in the console:
autocomplete-python: Ignoring keyup events due to autocomplete-plus settings.

**Comment by huargovfx** [comment]
It works, now, I had disabled the autocomplete plus, it is needed to work properly in GalliumOS
