### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-slick'

### ISSUE THREAD

**Issue by chenxq16** [autocomplete-python/autocomplete-python#305]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package 1.8.63

### Stack Trace

Uncaught Error: Cannot find module 'atom-slick'

```
At module.js:457

Error: Cannot find module 'atom-slick'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-python/lib/scope-helpers.coffee:1:9)
    at /packages/autocomplete-python/lib/scope-helpers.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-python/lib/provider.coffee:93:35)
    at constructor.load (/packages/autocomplete-python/lib/provider.coffee:88:8)
    at constructor.getSuggestions (/packages/autocomplete-python/lib/provider.coffee:423:6)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.8.63 
python-tools 0.6.9 
```

**Comment by Nonsensersunny** [comment]
There's something wrong with my Atom, when I code Python, it cannot complete automatically and the pop to warn me that something wronged with my autocmplete-python package.
