### ISSUE TITLE
issue installing package on atom with autocomplete-python 1.10.5

### ISSUE THREAD

**Issue by hsaichaitanya** [autocomplete-python/autocomplete-python#353]
### Prerequisites

* [ ] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by hsaichaitanya** [comment]
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.<anonymous> (C:\Users\sai_chaitan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\windows.js:12:36)
    at Object.<anonymous> (C:\Users\sai_chaitan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\support\windows.js:159:3)
    at Module.get_Module._compile (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/sai_chaitan/AppData/Local/atom/app-1.22.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\native-compile-cache.js:66:33)
    at Object.getSupport (C:\Users\sai_chaitan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\constants.js:20:30)
    at Object.get support [as support] (C:\Users\sai_chaitan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\state-controller.js:20:21)
    at Object.isKiteSupported (C:\Users\sai_chaitan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\state-controller.js:63:16)
    at Object.canInstallKite (C:\Users\sai_chaitan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\state-controller.js:99:17)
    at file:///C:/Users/sai_chaitan/.atom/packages/autocomplete-python/lib/main.coffee:185:36
    at Object._loadKite (file:///C:/Users/sai_chaitan/.atom/packages/autocomplete-python/lib/main.coffee:222:5)
    at Object.load (file:///C:/Users/sai_chaitan/.atom/packages/autocomplete-python/lib/main.coffee:239:6)
    at Object.activate (file:///C:/Users/sai_chaitan/.atom/packages/autocomplete-python/lib/main.coffee:246:8)
    at Package.module.exports.Package.activateNow (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:253:25)
    at C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:99:21)
    at C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:215:40)
    at PackageManager.activatePackage (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:690:42)
    at packagesToEnable.forEach.name (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:439:30)
    at C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:884:35)
    at Config.module.exports.Config.setRawValue (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:670:25)
    at Config.module.exports.Config.set (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:407:18)
    at Package.module.exports.Package.enable (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:84:32)
    at PackageManager.enablePackage (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:245:18)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\sai_chaitan\AppData\Local\atom\app-1.22.1\resources\app\node_modules\settings-view\lib\package-card.js:361:31)
