### ISSUE TITLE
Failed to activate the autocomplete-python package

### ISSUE THREAD

**Issue by satgar12** [autocomplete-python/autocomplete-python#358]
### Prerequisites

* [ ] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package 1.10.5

### Stack Trace

Failed to activate the autocomplete-python package

```
At Cannot read property 'providerManager' of null

TypeError: Cannot read property 'providerManager' of null
    at Object.consumeProvider (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/main.js:89:55)
    at Object.consumeProvider_2 (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/main.js:62:23)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:258:22)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:440:30)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
  3x -9:52.6.0 core:move-down (div.package-detail.panels-item)
  6x -9:50.5.0 core:move-up (div.package-detail.panels-item)
 35x -9:31.9.0 core:move-down (div.package-detail.panels-item)
 21x -8:14.9.0 core:backspace (input.hidden-input)
 20x -7:05.3.0 core:move-up (div.panels-item)
 16x -6:41.4.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-one-dark-ui)
 25x -6:18.4.0 core:move-up (div.panels-item)
  2x -6:08.9.0 core:move-down (div.panels-item)
 35x -6:08.2.0 core:move-up (div.panels-item)
 37x -4:39.6.0 core:move-down (div.package-detail.panels-item)
 40x -4:32.8.0 core:move-up (div.package-detail.panels-item)
  6x -3:50.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
predawn-syntax 1.0.4 
script 3.17.3 
```

**Comment by ycliu613** [comment]
same question to yours

**Comment by hakro** [comment]
Same problem here with a fresh stock install of Atom 1.27 and autocomplete-python 1.10.5
