### ISSUE TITLE
Flake 8 unsupported UNC path

### ISSUE THREAD

**Issue by FenryrMKIII** [autocomplete-python/autocomplete-python#381]
I receive the following error message when working on a mapped drive on Windows 10 : 

```
`Uncaught (in promise) Error: Path must be a valid path to a file or a directory.
    at C:\Users\XXX\AppData\Local\atom\app-1.27.2\resources\app\node_modules\@atom\nsfw\lib\src\index.js:97:17
    at tryCallOne (C:\Users\XXX\AppData\Local\atom\app-1.27.2\resources\app\node_modules\nodegit-promise\lib\core.js:37:18)
    at C:\Users\XXX\AppData\Local\atom\app-1.27.2\resources\app\node_modules\nodegit-promise\lib\core.js:103:21
    at flush (C:\Users\XXX\AppData\Local\atom\app-1.27.2\resources\app\node_modules\asap\raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
	
linter-flake8:: Flake8 returned an error '\\WebServerPath\Users\XXX\MyProject'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.`
```

I have found the following issue [13104](https://github.com/atom/atom/issues/13104) to be related when typing my error message on google but I can't figure out if this is indeed related or not and what to do to fix my issue ?

**Comment by FenryrMKIII** [comment]
For future reference : Managed to solve the issue by mapping the UNC path to a network drive as suggested in [221](\\D10.tes.local\te\NUC\MODEL_AND_CALCUL\SEVERE_ACCIDENTS)
