### ISSUE TITLE
Installing “autocomplete-python@1.10.10” failed.Show output… Compiler tools not found Packages that depend on modules that contain C/C++ code will fail to install. Read here for instructions on installing Python and Visual Studio. Run apm install --check after installing to test compiling a native module.

### ISSUE THREAD

**Issue by sureshnnr786** [autocomplete-python/autocomplete-python#395]
### Prerequisites

* [ ] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by sureshnnr786** [comment]
Installing “autocomplete-python@1.10.10” failed.

**Comment by sureshnnr786** [comment]
Installing “autocomplete-python@1.10.10” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v2.0.5/iojs-v2.0.5.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.5/iojs-v2.0.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\N SURESH\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\N SURESH\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=2.0.5" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\N SURESH\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
