### ISSUE TITLE
upgraded to 1.10.12 and now cannot activate

### ISSUE THREAD

**Issue by ahanjrah** [autocomplete-python/autocomplete-python#398]
[Enter steps to reproduce:]

1. Upgraded from 1.10.11 to 1.10.12
2. Restarted Atom and this error was displayed

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.3
**Thrown From**: [autocomplete-python](ssh://git@github.com/autocomplete-python/autocomplete-python) package 1.10.12

### Stack Trace

Failed to activate the autocomplete-python package

```
At Cannot find module './provider'

Error: Cannot find module './provider'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/autocomplete-python/lib/main.coffee:232:23)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.10.12 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
intentions 1.1.5 
kite 0.105.0 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.4 
```

**Comment by ahanjrah** [comment]
Nvm, I uninstalled and reinstalled again, it is working now. Please close this issue for now.

Thanks for the kick a@@ plugin though.
