### ISSUE TITLE
Installing “autocomplete-python@1.11.0” failed

### ISSUE THREAD

**Issue by AnkitKadam567** [autocomplete-python/autocomplete-python#403]
Installing “autocomplete-python@1.11.0” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...ies":{},"directories"'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ankit Kadam\.atom\.apm\_logs\2018-11-06T14_52_20_230Z-debug.log

**Comment by liberbell** [comment]
Me too.
MacOS 10.14

<pre>
99 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...882be098a393","tarbal'
99 verbose stack     at JSON.parse (<anonymous>)
99 verbose stack     at parseJson (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
99 verbose stack     at consumeBody.call.then.buffer (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
99 verbose stack     at <anonymous>
99 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
100 verbose cwd /private/var/folders/vt/7y_06kyd6853gzk4_rwn3gf40000gn/T/apm-install-dir-1181027-3317-nfjz2m.qz7m
101 verbose Darwin 18.2.0
102 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/username/.atom/.apm/.apmrc" "--userconfig" "/Users/username/.atom/.apmrc" "install" "https://www.atom.io/api/packages/autocomplete-python/versions/1.11.0/tarball" "--runtime=electron" "--target=2.0.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
103 verbose node v8.9.3
104 verbose npm  v6.2.0
105 error Unexpected end of JSON input while parsing near '...882be098a393","tarbal'
106 verbose exit [ 1, true ]
</pre>
