### ISSUE TITLE
Failing : hyperclick + python 3.8.0 + pyenv + virtualenv

### ISSUE THREAD

**Issue by portedison** [autocomplete-python/autocomplete-python#456]
#### Environment -
Python installed via, pyenv  versions are 2.7.12, 3.8.0
Virtualenv using pew to install.
Hyperclick 0.1.5
Autocomplete Python 1.17.0

Atom Config.
"autocomplete-python":
    extraPaths: "/Users/me/.virtualenvs/$PROJECT_NAME/lib/python3.8/site-packages"
    outputDebug: true
    pythonPaths: "/Users/me/.virtualenvs/$PROJECT_NAME/bin/python;
                            /Users/me/.virtualenvs/$PROJECT_NAME/bin/python3;
                            /Users/me/.pyenv/shims/python;/Users/me/.pyenv/shims/python3"
    showTooltips: false
    useKite: false

2.7.12 runs correctly.
Python hyperclick path - /Users/me/.pyenv/versions/2.7.12/lib/python2.7/python-package
Env hyperclick path - /Users/me/.virtualenvs/project/lib/python2.7/site-packages/pip-package

Issue is with version 3.8.0

#### Dev log -
autocomplete-python: Spawning python process...
log.coffee:5 autocomplete-python: User defined interpreters found Set(4) {"/Users/me/.virtualenvs/project/bin/python", "/Users/me/.virtualenvs/project/bin/python3", "/Users/me/.pyenv/shims/python", "/Users/me/.pyenv/shims/python3"}
autocomplete-python: Using interpreter /Users/me/.virtualenvs/project/bin/python
/Users/me/.atom/packages/autocomplete-python/lib/log.coffee:10 autocomplete-python: Pending requests: 0 Object
/Users/me/.atom/packages/autocomplete-python/lib/log.coffee:10 autocomplete-python: autocomplete-python traceback output: Traceback (most recent call last):
File "/Users/me/.atom/packages/autocomplete-python/lib/completion.py", line 378, in watch
self._process_request(request)
File "/Users/me/.atom/packages/autocomplete-python/lib/completion.py", line 338, in _process_request
script = jedi.api.Script(
TypeError: __init__() got an unexpected keyword argument 'source'
autocomplete-python: Forcing to resolve 1 promises
autocomplete-python: Killing python process after timeout

**Comment by portedison** [comment]
Also worth mentioning Jedi is installed on both python 2.7.12, and 3.8.0

**Comment by portedison** [comment]
Possible duplicates.
https://stackoverflow.com/questions/66830728/atom-editor-autocomplete-python-package-doesnt-work-jedi-problem
https://discuss.atom.io/t/atom-editor-autocomplete-python-package-doesnt-work-jedi-problem/82081

**Comment by chalegatech** [comment]
Thank you so much for this solution. I was racking my brains to get auto complete python work on Atom. Surprising that a previous version of Jedi works out and not the latest one. Hope the folks at Atom take notice.
