### ISSUE TITLE
Failed to activate the autocomplete-python package

### ISSUE THREAD

**Issue by Raihan0880** [autocomplete-python/autocomplete-python#459]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [autocomplete-python](ssh://git@github.com/autocomplete-python/autocomplete-python) package 1.17.0

### Stack Trace

Failed to activate the autocomplete-python package

```
At Cannot find module 'charenc'
Require stack:
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\md5\md5.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-api\lib\url-helpers.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-api\lib\index.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\account-manager.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\index.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\lib\main.coffee
- C:\Users\Raihan\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module 'charenc'
Require stack:
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\md5\md5.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-api\lib\url-helpers.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-api\lib\index.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\account-manager.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\index.js
- C:\Users\Raihan\.atom\packages\autocomplete-python\lib\main.coffee
- C:\Users\Raihan\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/autocomplete-python/node_modules/md5/md5.js:3:14
    at /packages/autocomplete-python/node_modules/md5/md5.js:160:3)
    at /packages/autocomplete-python/node_modules/md5/md5.js:162:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/autocomplete-python/node_modules/kite-api/lib/url-helpers.js:3:13)
    at /packages/autocomplete-python/node_modules/kite-api/lib/url-helpers.js:75:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/autocomplete-python/node_modules/kite-api/lib/index.js:19:14)
    at /packages/autocomplete-python/node_modules/kite-api/lib/index.js:570:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/autocomplete-python/node_modules/kite-installer/lib/account-manager.js:3:17)
    at /packages/autocomplete-python/node_modules/kite-installer/lib/account-manager.js:7:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/autocomplete-python/node_modules/kite-installer/lib/index.js:3:24)
    at /packages/autocomplete-python/node_modules/kite-installer/lib/index.js:80:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at Object._loadKite (/packages/autocomplete-python/lib/main.coffee:133:14)
    at Object.load (/packages/autocomplete-python/lib/main.coffee:241:19)
    at Object.activate (/packages/autocomplete-python/lib/main.coffee:248:21)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508863)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508275
    at Package.measure (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3505853)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508135
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508078)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:385612)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:380776
    at Array.forEach (<anonymous>)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:380760
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:337689
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:340177)
    at Config.setRawValue (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:337417)
    at Config.set (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:333211)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:335234)
    at Package.enable (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3505618)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:378379)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2718109)
```

### Commands

```
     -7:08.1.0 editor:newline (input.hidden-input)
  9x -7:05.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.17.0 
file-icons 2.1.47 
predawn-syntax 1.0.4 
script 3.32.2 
```

**Comment by Raihan0880** [comment]
i get this problem when i enable the package
